---
language: node_js
node_js: lts/*
sudo: required

services:
  - docker
  - mongodb

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

matrix:
  fast_finish: true

before_install:
  - npm install eslint html-lint csslint
  - sudo pip install yamllint

install: true

before_script:
  - "./tests/test-csslint.sh"
  - "./tests/test-eslint.sh"
  - "./tests/test-html-lint.sh"
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

jobs:
  include:
    - script: ./tests/test-docker.sh
    - script: >
        npm install --prefix containers/map-api &&
        npm test --prefix containers/map-api
