---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze" # Comment this line to use dynamic provisioning (paid)
  name: ca-claim
  labels:
    app: fitcoin-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze" # Comment this line to use dynamic provisioning (paid)
  name: fitcoin-state-claim
  labels:
    app: fitcoin-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze" # Comment this line to use dynamic provisioning (paid)
  name: shop-state-claim
  labels:
    app: shop-state-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
