apiVersion: v1
kind: Service
metadata:
  name: couchdb0
  labels:
    app: couchdb0
spec:
  type: ClusterIP
  ports:
    - port: 5984
  selector:
    app: couchdb0
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: couchdb0-deployment
  labels:
    app: couchdb0
spec:
  template:
    metadata:
      labels:
        app: couchdb0
    spec:
      containers:
      - image: hyperledger/fabric-couchdb:x86_64-1.0.2
        imagePullPolicy: Always
        name: couchdb0
        ports:
        - containerPort: 5984
          name: couchdb0
        env:
          - name: COUCHDB_USER
            value: ""
          - name: COUCHDB_PASSWORD
            value: ""
