apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:4.0.5-alpine
        imagePullPolicy: Always
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        name: redis
        ports:
        - containerPort: 6379
