apiVersion: v1
kind: Service
metadata:
  name: shop-peer
  labels:
    app: shop-peer
spec:
  type: ClusterIP
  ports:
    - port: 7051
      name: shop-port-1
    - port: 7053
      name: shop-port-2
  selector:
    app: shop-peer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shop-peer-deployment
  labels:
    app: shop-peer
spec:
  template:
    metadata:
      labels:
        app: shop-peer
    spec:
      containers:
      - image: anthonyamanse/shop-peer:latest
        imagePullPolicy: Always
        workingDir: /peer
        command: ["peer"]
        args: ["node", "start"]
        name: shop-peer
        ports:
        - containerPort: 7051
        - containerPort: 7053
        env:
          - name: CORE_PEER_ID
            value: "shop-peer"
          - name: CORE_PEER_ADDRESS
            value: "shop-peer:7051"
          - name: CORE_PEER_LISTENADDRESS
            value: 0.0.0.0:7051
          - name: CORE_PEER_EVENTS_ADDRESS
            value: 0.0.0.0:7053
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: "shop-peer:7051"
          - name: CORE_PEER_LOCALMSPID
            value: "ShopOrgMSP"
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: "couchdb0:5984"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            value: ""
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            value: ""
        envFrom:
          - configMapRef:
              name: peer-base-env
        volumeMounts:
          - name: dockersocket
            mountPath: /host/var/run/docker.sock
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock